(cl:defpackage smart_factory_sim-srv
  (:use )
  (:export
   "ASSIGNTASK"
   "<ASSIGNTASK-REQUEST>"
   "ASSIGNTASK-REQUEST"
   "<ASSIGNTASK-RESPONSE>"
   "ASSIGNTASK-RESPONSE"
   "PROCESSMATERIAL"
   "<PROCESSMATERIAL-REQUEST>"
   "PROCESSMATERIAL-REQUEST"
   "<PROCESSMATERIAL-RESPONSE>"
   "PROCESSMATERIAL-RESPONSE"
  ))

