# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from smart_factory_sim/MachineState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class MachineState(genpy.Message):
  _md5sum = "83c455b2e59b8c116d67ec85f20c9dc2"
  _type = "smart_factory_sim/MachineState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# 机器状态消息
int32 machine_id
string machine_type  # carding, drawing1, drawing2, roving
string status  # idle, processing, waiting, blocked
geometry_msgs/Point position
int32 materials_count
float32 efficiency

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['machine_id','machine_type','status','position','materials_count','efficiency']
  _slot_types = ['int32','string','string','geometry_msgs/Point','int32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       machine_id,machine_type,status,position,materials_count,efficiency

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MachineState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.machine_id is None:
        self.machine_id = 0
      if self.machine_type is None:
        self.machine_type = ''
      if self.status is None:
        self.status = ''
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.materials_count is None:
        self.materials_count = 0
      if self.efficiency is None:
        self.efficiency = 0.
    else:
      self.machine_id = 0
      self.machine_type = ''
      self.status = ''
      self.position = geometry_msgs.msg.Point()
      self.materials_count = 0
      self.efficiency = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.machine_id
      buff.write(_get_struct_i().pack(_x))
      _x = self.machine_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3dif().pack(_x.position.x, _x.position.y, _x.position.z, _x.materials_count, _x.efficiency))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 4
      (self.machine_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.machine_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.machine_type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.position.x, _x.position.y, _x.position.z, _x.materials_count, _x.efficiency,) = _get_struct_3dif().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.machine_id
      buff.write(_get_struct_i().pack(_x))
      _x = self.machine_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_3dif().pack(_x.position.x, _x.position.y, _x.position.z, _x.materials_count, _x.efficiency))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 4
      (self.machine_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.machine_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.machine_type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status = str[start:end]
      _x = self
      start = end
      end += 32
      (_x.position.x, _x.position.y, _x.position.z, _x.materials_count, _x.efficiency,) = _get_struct_3dif().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3dif = None
def _get_struct_3dif():
    global _struct_3dif
    if _struct_3dif is None:
        _struct_3dif = struct.Struct("<3dif")
    return _struct_3dif
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
