# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from smart_factory_sim/TaskStatus.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class TaskStatus(genpy.Message):
  _md5sum = "b60bd2ab3a7887e34ec8035f0abf6774"
  _type = "smart_factory_sim/TaskStatus"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """# 任务状态消息
int32 task_id
string task_type  # TRANSPORT, PROCESS
int32 priority
geometry_msgs/Point source
geometry_msgs/Point destination
string material_type
string status  # pending, assigned, in_progress, completed, failed
int32 assigned_robot_id

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['task_id','task_type','priority','source','destination','material_type','status','assigned_robot_id']
  _slot_types = ['int32','string','int32','geometry_msgs/Point','geometry_msgs/Point','string','string','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       task_id,task_type,priority,source,destination,material_type,status,assigned_robot_id

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(TaskStatus, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.task_id is None:
        self.task_id = 0
      if self.task_type is None:
        self.task_type = ''
      if self.priority is None:
        self.priority = 0
      if self.source is None:
        self.source = geometry_msgs.msg.Point()
      if self.destination is None:
        self.destination = geometry_msgs.msg.Point()
      if self.material_type is None:
        self.material_type = ''
      if self.status is None:
        self.status = ''
      if self.assigned_robot_id is None:
        self.assigned_robot_id = 0
    else:
      self.task_id = 0
      self.task_type = ''
      self.priority = 0
      self.source = geometry_msgs.msg.Point()
      self.destination = geometry_msgs.msg.Point()
      self.material_type = ''
      self.status = ''
      self.assigned_robot_id = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self.task_id
      buff.write(_get_struct_i().pack(_x))
      _x = self.task_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i6d().pack(_x.priority, _x.source.x, _x.source.y, _x.source.z, _x.destination.x, _x.destination.y, _x.destination.z))
      _x = self.material_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.assigned_robot_id
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.source is None:
        self.source = geometry_msgs.msg.Point()
      if self.destination is None:
        self.destination = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 4
      (self.task_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.task_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.task_type = str[start:end]
      _x = self
      start = end
      end += 52
      (_x.priority, _x.source.x, _x.source.y, _x.source.z, _x.destination.x, _x.destination.y, _x.destination.z,) = _get_struct_i6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.material_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.material_type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status = str[start:end]
      start = end
      end += 4
      (self.assigned_robot_id,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self.task_id
      buff.write(_get_struct_i().pack(_x))
      _x = self.task_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self
      buff.write(_get_struct_i6d().pack(_x.priority, _x.source.x, _x.source.y, _x.source.z, _x.destination.x, _x.destination.y, _x.destination.z))
      _x = self.material_type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.Struct('<I%ss'%length).pack(length, _x))
      _x = self.assigned_robot_id
      buff.write(_get_struct_i().pack(_x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.source is None:
        self.source = geometry_msgs.msg.Point()
      if self.destination is None:
        self.destination = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 4
      (self.task_id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.task_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.task_type = str[start:end]
      _x = self
      start = end
      end += 52
      (_x.priority, _x.source.x, _x.source.y, _x.source.z, _x.destination.x, _x.destination.y, _x.destination.z,) = _get_struct_i6d().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.material_type = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.material_type = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status = str[start:end].decode('utf-8', 'rosmsg')
      else:
        self.status = str[start:end]
      start = end
      end += 4
      (self.assigned_robot_id,) = _get_struct_i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_i6d = None
def _get_struct_i6d():
    global _struct_i6d
    if _struct_i6d is None:
        _struct_i6d = struct.Struct("<i6d")
    return _struct_i6d
