
local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 2.0
  
  # 局部地图尺寸（机器人周围2m范围）
  static_map: false
  rolling_window: true
  
  width: 4.0
  height: 4.0
  resolution: 0.05
  
  # 变换容忍度
  transform_tolerance: 0.5
