// Generated by gencpp from file smart_factory_sim/AssignTask.msg
// DO NOT EDIT!


#ifndef SMART_FACTORY_SIM_MESSAGE_ASSIGNTASK_H
#define SMART_FACTORY_SIM_MESSAGE_ASSIGNTASK_H

#include <ros/service_traits.h>


#include <smart_factory_sim/AssignTaskRequest.h>
#include <smart_factory_sim/AssignTaskResponse.h>


namespace smart_factory_sim
{

struct AssignTask
{

typedef AssignTaskRequest Request;
typedef AssignTaskResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AssignTask
} // namespace smart_factory_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::smart_factory_sim::AssignTask > {
  static const char* value()
  {
    return "3450a2182eb013df5d30a3ff5215b470";
  }

  static const char* value(const ::smart_factory_sim::AssignTask&) { return value(); }
};

template<>
struct DataType< ::smart_factory_sim::AssignTask > {
  static const char* value()
  {
    return "smart_factory_sim/AssignTask";
  }

  static const char* value(const ::smart_factory_sim::AssignTask&) { return value(); }
};


// service_traits::MD5Sum< ::smart_factory_sim::AssignTaskRequest> should match
// service_traits::MD5Sum< ::smart_factory_sim::AssignTask >
template<>
struct MD5Sum< ::smart_factory_sim::AssignTaskRequest>
{
  static const char* value()
  {
    return MD5Sum< ::smart_factory_sim::AssignTask >::value();
  }
  static const char* value(const ::smart_factory_sim::AssignTaskRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::smart_factory_sim::AssignTaskRequest> should match
// service_traits::DataType< ::smart_factory_sim::AssignTask >
template<>
struct DataType< ::smart_factory_sim::AssignTaskRequest>
{
  static const char* value()
  {
    return DataType< ::smart_factory_sim::AssignTask >::value();
  }
  static const char* value(const ::smart_factory_sim::AssignTaskRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::smart_factory_sim::AssignTaskResponse> should match
// service_traits::MD5Sum< ::smart_factory_sim::AssignTask >
template<>
struct MD5Sum< ::smart_factory_sim::AssignTaskResponse>
{
  static const char* value()
  {
    return MD5Sum< ::smart_factory_sim::AssignTask >::value();
  }
  static const char* value(const ::smart_factory_sim::AssignTaskResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::smart_factory_sim::AssignTaskResponse> should match
// service_traits::DataType< ::smart_factory_sim::AssignTask >
template<>
struct DataType< ::smart_factory_sim::AssignTaskResponse>
{
  static const char* value()
  {
    return DataType< ::smart_factory_sim::AssignTask >::value();
  }
  static const char* value(const ::smart_factory_sim::AssignTaskResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SMART_FACTORY_SIM_MESSAGE_ASSIGNTASK_H
