// Generated by gencpp from file smart_factory_sim/AssignTaskRequest.msg
// DO NOT EDIT!


#ifndef SMART_FACTORY_SIM_MESSAGE_ASSIGNTASKREQUEST_H
#define SMART_FACTORY_SIM_MESSAGE_ASSIGNTASKREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smart_factory_sim
{
template <class ContainerAllocator>
struct AssignTaskRequest_
{
  typedef AssignTaskRequest_<ContainerAllocator> Type;

  AssignTaskRequest_()
    : task_id(0)
    , robot_id(0)  {
    }
  AssignTaskRequest_(const ContainerAllocator& _alloc)
    : task_id(0)
    , robot_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _task_id_type;
  _task_id_type task_id;

   typedef int32_t _robot_id_type;
  _robot_id_type robot_id;





  typedef boost::shared_ptr< ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AssignTaskRequest_

typedef ::smart_factory_sim::AssignTaskRequest_<std::allocator<void> > AssignTaskRequest;

typedef boost::shared_ptr< ::smart_factory_sim::AssignTaskRequest > AssignTaskRequestPtr;
typedef boost::shared_ptr< ::smart_factory_sim::AssignTaskRequest const> AssignTaskRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator1> & lhs, const ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator2> & rhs)
{
  return lhs.task_id == rhs.task_id &&
    lhs.robot_id == rhs.robot_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator1> & lhs, const ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smart_factory_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "90e8cb05881303d06c77e2d96263ae84";
  }

  static const char* value(const ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x90e8cb05881303d0ULL;
  static const uint64_t static_value2 = 0x6c77e2d96263ae84ULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_factory_sim/AssignTaskRequest";
  }

  static const char* value(const ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 任务分配服务请求\n"
"int32 task_id\n"
"int32 robot_id\n"
;
  }

  static const char* value(const ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_id);
      stream.next(m.robot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AssignTaskRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_factory_sim::AssignTaskRequest_<ContainerAllocator>& v)
  {
    s << indent << "task_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.task_id);
    s << indent << "robot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.robot_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_FACTORY_SIM_MESSAGE_ASSIGNTASKREQUEST_H
