// Generated by gencpp from file smart_factory_sim/AssignTaskResponse.msg
// DO NOT EDIT!


#ifndef SMART_FACTORY_SIM_MESSAGE_ASSIGNTASKRESPONSE_H
#define SMART_FACTORY_SIM_MESSAGE_ASSIGNTASKRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smart_factory_sim
{
template <class ContainerAllocator>
struct AssignTaskResponse_
{
  typedef AssignTaskResponse_<ContainerAllocator> Type;

  AssignTaskResponse_()
    : success(false)
    , message()  {
    }
  AssignTaskResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AssignTaskResponse_

typedef ::smart_factory_sim::AssignTaskResponse_<std::allocator<void> > AssignTaskResponse;

typedef boost::shared_ptr< ::smart_factory_sim::AssignTaskResponse > AssignTaskResponsePtr;
typedef boost::shared_ptr< ::smart_factory_sim::AssignTaskResponse const> AssignTaskResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator1> & lhs, const ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator1> & lhs, const ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smart_factory_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "937c9679a518e3a18d831e57125ea522";
  }

  static const char* value(const ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x937c9679a518e3a1ULL;
  static const uint64_t static_value2 = 0x8d831e57125ea522ULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_factory_sim/AssignTaskResponse";
  }

  static const char* value(const ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 任务分配服务响应\n"
"bool success\n"
"string message\n"
"\n"
;
  }

  static const char* value(const ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AssignTaskResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_factory_sim::AssignTaskResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_FACTORY_SIM_MESSAGE_ASSIGNTASKRESPONSE_H
