// Generated by gencpp from file smart_factory_sim/MachineState.msg
// DO NOT EDIT!


#ifndef SMART_FACTORY_SIM_MESSAGE_MACHINESTATE_H
#define SMART_FACTORY_SIM_MESSAGE_MACHINESTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace smart_factory_sim
{
template <class ContainerAllocator>
struct MachineState_
{
  typedef MachineState_<ContainerAllocator> Type;

  MachineState_()
    : machine_id(0)
    , machine_type()
    , status()
    , position()
    , materials_count(0)
    , efficiency(0.0)  {
    }
  MachineState_(const ContainerAllocator& _alloc)
    : machine_id(0)
    , machine_type(_alloc)
    , status(_alloc)
    , position(_alloc)
    , materials_count(0)
    , efficiency(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _machine_id_type;
  _machine_id_type machine_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _machine_type_type;
  _machine_type_type machine_type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef int32_t _materials_count_type;
  _materials_count_type materials_count;

   typedef float _efficiency_type;
  _efficiency_type efficiency;





  typedef boost::shared_ptr< ::smart_factory_sim::MachineState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_factory_sim::MachineState_<ContainerAllocator> const> ConstPtr;

}; // struct MachineState_

typedef ::smart_factory_sim::MachineState_<std::allocator<void> > MachineState;

typedef boost::shared_ptr< ::smart_factory_sim::MachineState > MachineStatePtr;
typedef boost::shared_ptr< ::smart_factory_sim::MachineState const> MachineStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_factory_sim::MachineState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_factory_sim::MachineState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smart_factory_sim::MachineState_<ContainerAllocator1> & lhs, const ::smart_factory_sim::MachineState_<ContainerAllocator2> & rhs)
{
  return lhs.machine_id == rhs.machine_id &&
    lhs.machine_type == rhs.machine_type &&
    lhs.status == rhs.status &&
    lhs.position == rhs.position &&
    lhs.materials_count == rhs.materials_count &&
    lhs.efficiency == rhs.efficiency;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smart_factory_sim::MachineState_<ContainerAllocator1> & lhs, const ::smart_factory_sim::MachineState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smart_factory_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smart_factory_sim::MachineState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_factory_sim::MachineState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_factory_sim::MachineState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_factory_sim::MachineState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_factory_sim::MachineState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_factory_sim::MachineState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_factory_sim::MachineState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "83c455b2e59b8c116d67ec85f20c9dc2";
  }

  static const char* value(const ::smart_factory_sim::MachineState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x83c455b2e59b8c11ULL;
  static const uint64_t static_value2 = 0x6d67ec85f20c9dc2ULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_factory_sim::MachineState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_factory_sim/MachineState";
  }

  static const char* value(const ::smart_factory_sim::MachineState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_factory_sim::MachineState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 机器状态消息\n"
"int32 machine_id\n"
"string machine_type  # carding, drawing1, drawing2, roving\n"
"string status  # idle, processing, waiting, blocked\n"
"geometry_msgs/Point position\n"
"int32 materials_count\n"
"float32 efficiency\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::smart_factory_sim::MachineState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_factory_sim::MachineState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.machine_id);
      stream.next(m.machine_type);
      stream.next(m.status);
      stream.next(m.position);
      stream.next(m.materials_count);
      stream.next(m.efficiency);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MachineState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_factory_sim::MachineState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_factory_sim::MachineState_<ContainerAllocator>& v)
  {
    s << indent << "machine_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.machine_id);
    s << indent << "machine_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.machine_type);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "materials_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.materials_count);
    s << indent << "efficiency: ";
    Printer<float>::stream(s, indent + "  ", v.efficiency);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_FACTORY_SIM_MESSAGE_MACHINESTATE_H
