// Generated by gencpp from file smart_factory_sim/MaterialInfo.msg
// DO NOT EDIT!


#ifndef SMART_FACTORY_SIM_MESSAGE_MATERIALINFO_H
#define SMART_FACTORY_SIM_MESSAGE_MATERIALINFO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace smart_factory_sim
{
template <class ContainerAllocator>
struct MaterialInfo_
{
  typedef MaterialInfo_<ContainerAllocator> Type;

  MaterialInfo_()
    : id(0)
    , type()
    , position()
    , location()
    , batch_id(0)  {
    }
  MaterialInfo_(const ContainerAllocator& _alloc)
    : id(0)
    , type(_alloc)
    , position(_alloc)
    , location(_alloc)
    , batch_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _type_type;
  _type_type type;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _location_type;
  _location_type location;

   typedef int32_t _batch_id_type;
  _batch_id_type batch_id;





  typedef boost::shared_ptr< ::smart_factory_sim::MaterialInfo_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_factory_sim::MaterialInfo_<ContainerAllocator> const> ConstPtr;

}; // struct MaterialInfo_

typedef ::smart_factory_sim::MaterialInfo_<std::allocator<void> > MaterialInfo;

typedef boost::shared_ptr< ::smart_factory_sim::MaterialInfo > MaterialInfoPtr;
typedef boost::shared_ptr< ::smart_factory_sim::MaterialInfo const> MaterialInfoConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_factory_sim::MaterialInfo_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_factory_sim::MaterialInfo_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smart_factory_sim::MaterialInfo_<ContainerAllocator1> & lhs, const ::smart_factory_sim::MaterialInfo_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.type == rhs.type &&
    lhs.position == rhs.position &&
    lhs.location == rhs.location &&
    lhs.batch_id == rhs.batch_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smart_factory_sim::MaterialInfo_<ContainerAllocator1> & lhs, const ::smart_factory_sim::MaterialInfo_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smart_factory_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smart_factory_sim::MaterialInfo_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_factory_sim::MaterialInfo_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_factory_sim::MaterialInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_factory_sim::MaterialInfo_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_factory_sim::MaterialInfo_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_factory_sim::MaterialInfo_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_factory_sim::MaterialInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b98b1aedcf605a3fb21632bdda789d0";
  }

  static const char* value(const ::smart_factory_sim::MaterialInfo_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b98b1aedcf605a3ULL;
  static const uint64_t static_value2 = 0xfb21632bdda789d0ULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_factory_sim::MaterialInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_factory_sim/MaterialInfo";
  }

  static const char* value(const ::smart_factory_sim::MaterialInfo_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_factory_sim::MaterialInfo_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 物料信息消息\n"
"int32 id\n"
"string type  # empty, green, yellow, red\n"
"geometry_msgs/Point position\n"
"string location  # 物料所在位置\n"
"int32 batch_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::smart_factory_sim::MaterialInfo_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_factory_sim::MaterialInfo_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.type);
      stream.next(m.position);
      stream.next(m.location);
      stream.next(m.batch_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MaterialInfo_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_factory_sim::MaterialInfo_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_factory_sim::MaterialInfo_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.id);
    s << indent << "type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.type);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "location: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.location);
    s << indent << "batch_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.batch_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_FACTORY_SIM_MESSAGE_MATERIALINFO_H
