// Generated by gencpp from file smart_factory_sim/ProcessMaterialResponse.msg
// DO NOT EDIT!


#ifndef SMART_FACTORY_SIM_MESSAGE_PROCESSMATERIALRESPONSE_H
#define SMART_FACTORY_SIM_MESSAGE_PROCESSMATERIALRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smart_factory_sim
{
template <class ContainerAllocator>
struct ProcessMaterialResponse_
{
  typedef ProcessMaterialResponse_<ContainerAllocator> Type;

  ProcessMaterialResponse_()
    : success(false)
    , message()
    , processed_count(0)  {
    }
  ProcessMaterialResponse_(const ContainerAllocator& _alloc)
    : success(false)
    , message(_alloc)
    , processed_count(0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _message_type;
  _message_type message;

   typedef int32_t _processed_count_type;
  _processed_count_type processed_count;





  typedef boost::shared_ptr< ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ProcessMaterialResponse_

typedef ::smart_factory_sim::ProcessMaterialResponse_<std::allocator<void> > ProcessMaterialResponse;

typedef boost::shared_ptr< ::smart_factory_sim::ProcessMaterialResponse > ProcessMaterialResponsePtr;
typedef boost::shared_ptr< ::smart_factory_sim::ProcessMaterialResponse const> ProcessMaterialResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator1> & lhs, const ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.message == rhs.message &&
    lhs.processed_count == rhs.processed_count;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator1> & lhs, const ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smart_factory_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ccb941f6e14bbd3e1c8703c506a1fdc2";
  }

  static const char* value(const ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xccb941f6e14bbd3eULL;
  static const uint64_t static_value2 = 0x1c8703c506a1fdc2ULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_factory_sim/ProcessMaterialResponse";
  }

  static const char* value(const ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 物料处理服务响应\n"
"bool success\n"
"string message\n"
"int32 processed_count\n"
"\n"
;
  }

  static const char* value(const ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.message);
      stream.next(m.processed_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProcessMaterialResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_factory_sim::ProcessMaterialResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.message);
    s << indent << "processed_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.processed_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_FACTORY_SIM_MESSAGE_PROCESSMATERIALRESPONSE_H
