// Generated by gencpp from file smart_factory_sim/ProcessMaterialRequest.msg
// DO NOT EDIT!


#ifndef SMART_FACTORY_SIM_MESSAGE_PROCESSMATERIALREQUEST_H
#define SMART_FACTORY_SIM_MESSAGE_PROCESSMATERIALREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace smart_factory_sim
{
template <class ContainerAllocator>
struct ProcessMaterialRequest_
{
  typedef ProcessMaterialRequest_<ContainerAllocator> Type;

  ProcessMaterialRequest_()
    : machine_id(0)
    , material_ids()  {
    }
  ProcessMaterialRequest_(const ContainerAllocator& _alloc)
    : machine_id(0)
    , material_ids(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _machine_id_type;
  _machine_id_type machine_id;

   typedef std::vector<int32_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<int32_t>> _material_ids_type;
  _material_ids_type material_ids;





  typedef boost::shared_ptr< ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ProcessMaterialRequest_

typedef ::smart_factory_sim::ProcessMaterialRequest_<std::allocator<void> > ProcessMaterialRequest;

typedef boost::shared_ptr< ::smart_factory_sim::ProcessMaterialRequest > ProcessMaterialRequestPtr;
typedef boost::shared_ptr< ::smart_factory_sim::ProcessMaterialRequest const> ProcessMaterialRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator1> & lhs, const ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator2> & rhs)
{
  return lhs.machine_id == rhs.machine_id &&
    lhs.material_ids == rhs.material_ids;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator1> & lhs, const ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smart_factory_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e881f9e53c5fd123ff75bd7f47c028ae";
  }

  static const char* value(const ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe881f9e53c5fd123ULL;
  static const uint64_t static_value2 = 0xff75bd7f47c028aeULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_factory_sim/ProcessMaterialRequest";
  }

  static const char* value(const ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 物料处理服务请求\n"
"int32 machine_id\n"
"int32[] material_ids\n"
;
  }

  static const char* value(const ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.machine_id);
      stream.next(m.material_ids);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ProcessMaterialRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_factory_sim::ProcessMaterialRequest_<ContainerAllocator>& v)
  {
    s << indent << "machine_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.machine_id);
    s << indent << "material_ids[]" << std::endl;
    for (size_t i = 0; i < v.material_ids.size(); ++i)
    {
      s << indent << "  material_ids[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.material_ids[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_FACTORY_SIM_MESSAGE_PROCESSMATERIALREQUEST_H
