// Generated by gencpp from file smart_factory_sim/ProcessMaterial.msg
// DO NOT EDIT!


#ifndef SMART_FACTORY_SIM_MESSAGE_PROCESSMATERIAL_H
#define SMART_FACTORY_SIM_MESSAGE_PROCESSMATERIAL_H

#include <ros/service_traits.h>


#include <smart_factory_sim/ProcessMaterialRequest.h>
#include <smart_factory_sim/ProcessMaterialResponse.h>


namespace smart_factory_sim
{

struct ProcessMaterial
{

typedef ProcessMaterialRequest Request;
typedef ProcessMaterialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ProcessMaterial
} // namespace smart_factory_sim


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::smart_factory_sim::ProcessMaterial > {
  static const char* value()
  {
    return "4208032b26373306627bcd16215de808";
  }

  static const char* value(const ::smart_factory_sim::ProcessMaterial&) { return value(); }
};

template<>
struct DataType< ::smart_factory_sim::ProcessMaterial > {
  static const char* value()
  {
    return "smart_factory_sim/ProcessMaterial";
  }

  static const char* value(const ::smart_factory_sim::ProcessMaterial&) { return value(); }
};


// service_traits::MD5Sum< ::smart_factory_sim::ProcessMaterialRequest> should match
// service_traits::MD5Sum< ::smart_factory_sim::ProcessMaterial >
template<>
struct MD5Sum< ::smart_factory_sim::ProcessMaterialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::smart_factory_sim::ProcessMaterial >::value();
  }
  static const char* value(const ::smart_factory_sim::ProcessMaterialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::smart_factory_sim::ProcessMaterialRequest> should match
// service_traits::DataType< ::smart_factory_sim::ProcessMaterial >
template<>
struct DataType< ::smart_factory_sim::ProcessMaterialRequest>
{
  static const char* value()
  {
    return DataType< ::smart_factory_sim::ProcessMaterial >::value();
  }
  static const char* value(const ::smart_factory_sim::ProcessMaterialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::smart_factory_sim::ProcessMaterialResponse> should match
// service_traits::MD5Sum< ::smart_factory_sim::ProcessMaterial >
template<>
struct MD5Sum< ::smart_factory_sim::ProcessMaterialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::smart_factory_sim::ProcessMaterial >::value();
  }
  static const char* value(const ::smart_factory_sim::ProcessMaterialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::smart_factory_sim::ProcessMaterialResponse> should match
// service_traits::DataType< ::smart_factory_sim::ProcessMaterial >
template<>
struct DataType< ::smart_factory_sim::ProcessMaterialResponse>
{
  static const char* value()
  {
    return DataType< ::smart_factory_sim::ProcessMaterial >::value();
  }
  static const char* value(const ::smart_factory_sim::ProcessMaterialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SMART_FACTORY_SIM_MESSAGE_PROCESSMATERIAL_H
