// Generated by gencpp from file smart_factory_sim/TaskStatus.msg
// DO NOT EDIT!


#ifndef SMART_FACTORY_SIM_MESSAGE_TASKSTATUS_H
#define SMART_FACTORY_SIM_MESSAGE_TASKSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace smart_factory_sim
{
template <class ContainerAllocator>
struct TaskStatus_
{
  typedef TaskStatus_<ContainerAllocator> Type;

  TaskStatus_()
    : task_id(0)
    , task_type()
    , priority(0)
    , source()
    , destination()
    , material_type()
    , status()
    , assigned_robot_id(0)  {
    }
  TaskStatus_(const ContainerAllocator& _alloc)
    : task_id(0)
    , task_type(_alloc)
    , priority(0)
    , source(_alloc)
    , destination(_alloc)
    , material_type(_alloc)
    , status(_alloc)
    , assigned_robot_id(0)  {
  (void)_alloc;
    }



   typedef int32_t _task_id_type;
  _task_id_type task_id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _task_type_type;
  _task_type_type task_type;

   typedef int32_t _priority_type;
  _priority_type priority;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _source_type;
  _source_type source;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _destination_type;
  _destination_type destination;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _material_type_type;
  _material_type_type material_type;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;

   typedef int32_t _assigned_robot_id_type;
  _assigned_robot_id_type assigned_robot_id;





  typedef boost::shared_ptr< ::smart_factory_sim::TaskStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::smart_factory_sim::TaskStatus_<ContainerAllocator> const> ConstPtr;

}; // struct TaskStatus_

typedef ::smart_factory_sim::TaskStatus_<std::allocator<void> > TaskStatus;

typedef boost::shared_ptr< ::smart_factory_sim::TaskStatus > TaskStatusPtr;
typedef boost::shared_ptr< ::smart_factory_sim::TaskStatus const> TaskStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::smart_factory_sim::TaskStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::smart_factory_sim::TaskStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::smart_factory_sim::TaskStatus_<ContainerAllocator1> & lhs, const ::smart_factory_sim::TaskStatus_<ContainerAllocator2> & rhs)
{
  return lhs.task_id == rhs.task_id &&
    lhs.task_type == rhs.task_type &&
    lhs.priority == rhs.priority &&
    lhs.source == rhs.source &&
    lhs.destination == rhs.destination &&
    lhs.material_type == rhs.material_type &&
    lhs.status == rhs.status &&
    lhs.assigned_robot_id == rhs.assigned_robot_id;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::smart_factory_sim::TaskStatus_<ContainerAllocator1> & lhs, const ::smart_factory_sim::TaskStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace smart_factory_sim

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::smart_factory_sim::TaskStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::smart_factory_sim::TaskStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_factory_sim::TaskStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::smart_factory_sim::TaskStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_factory_sim::TaskStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::smart_factory_sim::TaskStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::smart_factory_sim::TaskStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b60bd2ab3a7887e34ec8035f0abf6774";
  }

  static const char* value(const ::smart_factory_sim::TaskStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb60bd2ab3a7887e3ULL;
  static const uint64_t static_value2 = 0x4ec8035f0abf6774ULL;
};

template<class ContainerAllocator>
struct DataType< ::smart_factory_sim::TaskStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "smart_factory_sim/TaskStatus";
  }

  static const char* value(const ::smart_factory_sim::TaskStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::smart_factory_sim::TaskStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 任务状态消息\n"
"int32 task_id\n"
"string task_type  # TRANSPORT, PROCESS\n"
"int32 priority\n"
"geometry_msgs/Point source\n"
"geometry_msgs/Point destination\n"
"string material_type\n"
"string status  # pending, assigned, in_progress, completed, failed\n"
"int32 assigned_robot_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::smart_factory_sim::TaskStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::smart_factory_sim::TaskStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task_id);
      stream.next(m.task_type);
      stream.next(m.priority);
      stream.next(m.source);
      stream.next(m.destination);
      stream.next(m.material_type);
      stream.next(m.status);
      stream.next(m.assigned_robot_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::smart_factory_sim::TaskStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::smart_factory_sim::TaskStatus_<ContainerAllocator>& v)
  {
    s << indent << "task_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.task_id);
    s << indent << "task_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.task_type);
    s << indent << "priority: ";
    Printer<int32_t>::stream(s, indent + "  ", v.priority);
    s << indent << "source: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.source);
    s << indent << "destination: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.destination);
    s << indent << "material_type: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.material_type);
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
    s << indent << "assigned_robot_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.assigned_robot_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SMART_FACTORY_SIM_MESSAGE_TASKSTATUS_H
